In [1]:
import numpy as np
from tensorflow import keras
import tensorflow
from recorder import Recorder
import matplotlib.pyplot as plt
# import scipy
# # import librosa
# # from librosa import display
# # from IPython.display import Audio
# from scipy.fft import fft, fftfreq
import numpy as np
import cv2


def resize_image(image, width, height):
    """Resizes an image to a specified width and height."""
    resized_image = cv2.resize(image, (width, height))
    return resized_image

def convert_to_rgb(image):
    """Converts an image to RGB color space."""
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    return image
    

def predict_class(image):
    model = tensorflow.keras.models.load_model('keras_model.h5',compile=False)
    image = cv2.resize(image,(224,224))
    data = np.expand_dims(image, axis=0)
    prediction = model.predict(data)
    print(tensorflow.round(prediction))
    # plt.imshow(image)
    # plt.title("Image")
    return prediction[0][0]

def main():
    cap = cv2.VideoCapture('vid.webm')
    jat = cv2.imread('1.jpg', 1)
    jat_resized = resize_image(jat, 500, 500)
    # jat_resized = convert_to_rgb(jat_resized)
    threshold = 0.9
    count = 0
    while True:
        success, img = cap.read()
        image = img
        dimage = cv2.fastNlMeansDenoising(img, None, 10, 7, 21)
        image = cv2.resize(dimage,(224,224))
        # fig = plt.figure()
        # ax = fig.add_subplot(111)
        # ax.imshow(image)
        # plt.title("Image")
        # plt.show()
        probability = predict_class(image)
        if probability > threshold:
            count = count + 1
            print(f"Ambulance detected: {count}")
        if count == 6:
            count = 0
            cv2.imwrite('ambulance.jpg', image)
            cv2.destroyWindow('Image')
            cv2.imshow('found',jat_resized)
            cv2.namedWindow('found', cv2.WINDOW_FULLSCREEN)
            cv2.waitKey(0)
            break
            
        cv2.imshow('Image', image)
        cv2.waitKey(1)
       

if __name__ == '__main__':
    main()


1/1 [==============================] - 2s 2s/step
tf.Tensor([[0. 1. 0. 0.]], shape=(1, 4), dtype=float32)
1/1 [==============================] - 1s 757ms/step
tf.Tensor([[1. 0. 0. 0.]], shape=(1, 4), dtype=float32)
Ambulance detected: 1
1/1 [==============================] - 1s 761ms/step
tf.Tensor([[1. 0. 0. 0.]], shape=(1, 4), dtype=float32)
1/1 [==============================] - 1s 612ms/step
tf.Tensor([[1. 0. 0. 0.]], shape=(1, 4), dtype=float32)
Ambulance detected: 2
1/1 [==============================] - 1s 647ms/step
tf.Tensor([[1. 0. 0. 0.]], shape=(1, 4), dtype=float32)
1/1 [==============================] - 1s 601ms/step
tf.Tensor([[1. 0. 0. 0.]], shape=(1, 4), dtype=float32)
1/1 [==============================] - 1s 804ms/step
tf.Tensor([[1. 0. 0. 0.]], shape=(1, 4), dtype=float32)
1/1 [==============================] - 1s 775ms/step
tf.Tensor([[1. 0. 0. 0.]], shape=(1, 4), dtype=float32)
Ambulance detected: 3
1/1 [==============================] - 1s 687ms/step
tf.Tensor([[